### ISSUE TITLE
How to create Gosso.jar from the command-line? 

### ISSUE THREAD

**Issue by dvklopfenstein** [pwac092/gossto#4]
Thank you for your fantastic papers, (Yang 2012 and Canista 2014). They are clear, enjoyable to read, and thought-provoking.

I know I can download a Gossto.jar file, but what are the commands to create a jar file from the files located here: https://github.com/pwac092/gossto

Thank you again for your papers. Thank you for your time.

**Comment by alfonsoeromero** [comment]
Dear dvklopfenstein,

Thank you very much for your interest in Gossto. We are very grateful for your kind comments.

In order to make the building process of Gossto easier, we updated the git repository to follow the classic structure of a Java project. It now has all the Java sources under the src directory, and a better Readme file. Building is provided via the "ant" tool, which should be easily available in any system. Besides, the project can easily be imported into any popular IDE and use the provided build.xml script for building the Gossto jar.

I hope we have solved your issue. Please let us know if things are easier now and whether you have any problem with it.

Thank you.

**Comment by dvklopfenstein** [comment]
Dr Romero,

Thank you so much for your speedy reply and amazingly fast update. This is great.

The paper, _Improving GO semantic similarity measures by exploring the ontology beneath the terms and modelling uncertainty_ have such interesting ideas. It is helpful to have your code to complement the paper.

I will close this issue now.

Thank you for your time and for your fast, clear code.

Regards,

DV
